/*
 * SimpleKart E-commerce API
 *
 * API for an imaginary E-Commerce store to demonstrate API Builder capabilities in Postman
 *
 * OpenAPI spec version: 1.0.0
 * Contact: simplekart@postman.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Get items from the database
        /// </summary>
        /// <remarks>Pull a list of items from item database</remarks>
        /// <param name="list">Number of items to be displayed</param>
        /// <response code="200">OK - Successful pull of items</response>
        [HttpGet]
        [Route("/items")]
        [ValidateModelState]
        [SwaggerOperation("GetItems")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Items>), description: "OK - Successful pull of items")]
        public virtual IActionResult GetItems([FromQuery][Range(4, 15)]int? list)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Items>));
            string exampleJson = null;
            exampleJson = "[ \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\", \"6\" ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Items>>(exampleJson)
                        : default(List<Items>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
